{% set version = "4.1.1" %}

package:
  name: runps
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/runps/runps-{{ version }}.tar.gz
  sha256: 2d8bc61a245bca605f6c9ee2030846d53c51478528222b92993802b309676b53

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python
    - sh  # [not win]


test:
  imports:
    - runps
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/xapple/runps/
  summary: 'A small python utility for launching external processes easily..'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xapple
