{% set version = "4.1.2" %}

package:
  name: runps
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/runps/runps-{{ version }}.tar.gz
  sha256: c51854f0de90740939688ac79fb0b6897328514c2297fbd1a215cd39fd0d7424

build:
  number: 0

requirements:
  build:
    - python      # [build_platform != target_platform]
    - pip         # [build_platform != target_platform]
    - setuptools  # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python
    - sh  # [not win]


test:
  imports:
    - runps    # [build_platform == target_platform]
  requires:
    - pip      # [build_platform == target_platform]
  commands:
    - pip check  # [build_platform == target_platform]

about:
  home: https://github.com/xapple/runps/
  summary: "A small python utility for launching external processes easily.."
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xapple
